### ISSUE TITLE
Broken 'related' links

### ISSUE THREAD

**Issue by dclucas** [agco/hapi-harvester#38]
Long one, so please bear with me. And if this should be split in multiple issues, well, feel free to :)

I have deployed a hapi-harvester sample at cloud9. It is not up all the time, so let me give you some sample urls and payloads.

When I hit this URL: https://hapi-harvester-sample-dclucas.c9users.io/products/ffb9294c-4ad4-41be-bd3a-a3582fd4653f

I get this payload:

```javascript
{
  "data": [
    {
      "type": "products",
      "relationships": {
        "brands": {
          "id": "aa780d0d-a46e-41f1-aeb5-cd29b20848f5",
          "type": "brands",
          "links": {
            "related": "http://dclucas-hapi-harvester-sample-2303305:8080/products/ffb9294c-4ad4-41be-bd3a-a3582fd4653f/brands/aa780d0d-a46e-41f1-aeb5-cd29b20848f5"
          }
        }
      },
      "attributes": {
        "description": "MT800C"
      },
      "id": "ffb9294c-4ad4-41be-bd3a-a3582fd4653f"
    }
  ]
}
```

There are a couple of issues with the data.relationships.brands.links.related info:
1. the domain is resolving to something internal to cloud9. In case this was restricted to cloud9 it would be a low severity issue, but probably other solutions that do DNS redirection (heroku, potentially and quite surely an internal dokku solution) will face the same problem. Link should either be relative or resolved to the request's DNS;

2. even if I edit the url and point it to a reachable domain (https://hapi-harvester-sample-dclucas.c9users.io/products/ffb9294c-4ad4-41be-bd3a-a3582fd4653f/brands/aa780d0d-a46e-41f1-aeb5-cd29b20848f5), I still get a 404.

**Comment by kristofsajdak** [comment]
Personally I prefer relative urls, less data to send across and no configuration hassle if you are behind a load balancer.

It does seem though that there are a couple of issues with our implementation of [jsonapi 1.0 relationships](http://jsonapi.org/format/#document-resource-object-relationships) 

Let's say we go with relative urls, as far as I understand the related link then should be :  

```javascript
"related": "/products/ffb9294c-4ad4-41be-bd3a-a3582fd4653f/brands"
````        
and when you follow the link it should be rewritten internally in harvester as :  

```shell
/brands/aa780d0d-a46e-41f1-aeb5-cd29b20848f5 
```

Right now our codebase has a function to do all that, but it's checking for a 'relationship link' url rather than a 'related link' url : https://github.com/agco/hapi-harvester/blob/develop/lib/plugin.js#L235

There is a clear difference between :

````shell
GET /products/ffb9294c-4ad4-41be-bd3a-a3582fd4653f/brands
````
and 

```shell
GET /products/ffb9294c-4ad4-41be-bd3a-a3582fd4653f/relationships/brands
````

Proposing we make the following changes: 

1) Remove 'baseUri' and 'doc.id' when outputting the related links : 
https://github.com/agco/hapi-harvester/blob/develop/lib/plugin.js#L353

2) The onRequest 'related link' rewrite should match format 
````shell
/{originating_resources}/{id}/{relationship}
````
rather than 
````shell
/{originating_resources}/{id}/relationships/{relationship} 
````
https://github.com/agco/hapi-harvester/blob/develop/lib/plugin.js#L235

**Comment by blabno** [comment]
@dclucas You cannot fetch relationships by id. Only by it's name is (Yes, the generated link is invalid).

**Comment by blabno** [comment]
@kristofsajdak I think that [specs](http://jsonapi.org/format/#fetching-relationships) clearly states that following is correct:
```
/{originating_resources}/{id}/relationships/{relationship} 
```

**Comment by kristofsajdak** [comment]
The url is indeed correct according to the spec, however this is a 'relationship link' url rather than a 'related resource link', there is a difference 

Let's take the following example from jsonapi.org

```` javascript
"relationships": {
    "author": {
      "links": {
        "self": "http://example.com/articles/1/relationships/author",
        "related": "http://example.com/articles/1/author"
      },
      "data": { "type": "people", "id": "9" }
    }
  }
````

'http://example.com/articles/1/relationships/author' is the relationship link
'http://example.com/articles/1/author' is the related resource link

**Comment by blabno** [comment]
Hm, so what is self for? To manage the link only?

**Comment by kristofsajdak** [comment]
Yes, pretty much. Explained here : http://jsonapi.org/format/#crud-updating-relationships

**Comment by mavdi** [comment]
```baseUri``` made little sense since it requires it to be declared when we setup the API (we have to somehow pass down the domain name), which I dislike. But how does dropping it affect our JSON API compliance?

**Comment by kristofsajdak** [comment]
couldn't find any mention in the spec that the urls should be absolute, so I'm guessing we should be ok here.

**Comment by kristofsajdak** [comment]
Added a PR with fixes for this issue. I removed the baseUri from our code, but happy to change in case we think we need absolute urls. 

https://github.com/agco/hapi-harvester/pull/43
